name: ML
channels:
  - defaults
  - conda-forge
dependencies:
  - imbalanced-learn=0.9.1
  - jupyter=1.0.0
  - matplotlib=3.5.2
  - numpy=1.21.5
  - pandas=1.4.4
  - pip=22.1.2
  - python=3.10.4
  - scikit-learn=1.1.1
  - scipy=1.7.3
